name: Run Scraper

on:
  # 9 AM – 12 AM (midnight) ET, every 30 min, Mon–Fri
  schedule:
    - cron: '*/30 13-23 * * 1-5'   # 09:00–23:30 ET
    - cron: '*/30 0-4 * * 2-6'     # 00:00–04:00 ET  (Tue–Sat UTC)
  workflow_dispatch:               # manual trigger button

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"   # quotes → string, not 3.1

      # Persist .last_seen.txt between runs
      - name: Restore cache for last_seen
        uses: actions/cache@v4
        id: cache
        with:
          path: .last_seen.txt
          key: last-seen-cache

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: |
          python - <<'PY'
          import main
          # Call your Cloud‑Function‑style handler once per run
          main.scrape_handler(None)
          PY

      - name: Save last_seen cache
        if: always()                    
        uses: actions/cache/save@v4
        with:
          path: .last_seen.txt
          key: last-seen-cache