name: Run Scraper 

on:
  schedule:
    # From 9:00 AM to 11:30 PM ET (13:00–23:30 UTC)
    - cron: '*/30 13-23 * * 1-5'
    # From 12:00 AM to 12:00 AM ET (00:00–04:00 UTC on next day), but still "Monday to Friday" local
    - cron: '*/30 0-4 * * 2-6'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Restore cache for last_seen
        id: cache
        uses: actions/cache@v4
        with:
          path: .last_seen.txt
          key: last-seen-cache

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python main.py

      - name: Save updated last_seen to cache
        if: always()
        run: echo "Done"
        # no need to update the cache explicitly — same cache key reuses updated file
